Increment11
t1mon-ggg/go_shortner pull request #7
Opened 2022-04-22 20:32 UTC by t1mon-ggg

2022-04-26 10:59 UTC, rktkov requested changes

2022-04-26 10:59 UTC, rktkov commented on internal/app/helpers/types.go
> +package helpers
Это  больше похоже на модель, а не helper. Более того, сущность дата у тебя используется в интерфейсе

2022-04-26 10:59 UTC, rktkov commented on internal/app/storage/memory.go
> +type MemDB map[string]helpers.WebData
Почему не используется тип Data из того же пакета helpers?

2022-04-26 10:59 UTC, rktkov commented on internal/app/storage/memory.go
> +	if db == nil {
Такого не может быть. Во время выполнения возникнет паника - вызов метода у неинициализированного объекта.

2022-04-26 10:59 UTC, rktkov commented on internal/app/storage/memory.go
> +		entry := m[i]
Лишнее действие. Можно использовать конструкцию языка:
for i, entry := range m

2022-04-26 10:59 UTC, rktkov commented on internal/app/storage/filestorage.go
> +		if len(entry.Short) != 0 {
Повторяется один и тот же код, что и в хранении в памяти. Очень просится одно место, куда этот код можно поместить а здесь и в файле memory.go вызывать всего лишь один метод.

2022-04-26 10:59 UTC, rktkov commented on internal/app/storage/database.go
> +	for i := range data {
Вот это прям очень плохой метод! Я бы посмотрел в сторону транзакции и подумал, как бы все с помощью них обернуть.

2022-04-26 10:59 UTC, rktkov commented on internal/app/helpers/types.go
> +type WebData struct {
Выбрана очень не удобная схема хранения. Из-за этого весь код, связанный с ее использованием громоздкий и "багоопасный".
Стоит начать с того, чтобы пересмотреть модель данных, а после с учетом новой модели внести изменения в реализации репозиториев.

2022-04-26 10:59 UTC, rktkov commented on cmd/shortener/shortener.go
> +package main
файл надо переименовать в main

2022-04-26 10:59 UTC, rktkov commented on cmd/shortener/shortener.go
> +	AppData := webhandlers.NewApp()
Инициализацию конфига стоит скрыть в пакете конфига. А отсюда вызывать только один метод - Init для сущности конфига

2022-04-26 10:59 UTC, rktkov commented on internal/app/webhandlers/handler.go
> +func (db *app) Router(r chi.Router) {
Почему экземплярный параметр назван db? Лучше придумать другое имя.

2022-04-26 10:59 UTC, rktkov commented on internal/app/webhandlers/handler.go
> +func DecompressRequest(next http.Handler) http.Handler {
Лучше вынести в отдельный пакет

2022-04-26 10:59 UTC, rktkov commented on internal/app/webhandlers/handler.go
> +func TimeTracer(next http.Handler) http.Handler {
см. комментарий выше

2022-04-26 10:59 UTC, rktkov commented on cmd/shortener/shortener.go
> +	AppData := webhandlers.NewApp()
Переименовать с маленькой буквы.

2022-04-30 06:21 UTC, asmyasnikov reviewed
А почему не исправлены или аргументированно не отвергнуты замечания предыдущего ревьювера?

2022-04-30 06:21 UTC, asmyasnikov commented on cmd/shortener/main.go
> +	"github.com/go-chi/chi"
goimports - нужна пробельная строка

2022-04-30 07:24 UTC, t1mon-ggg commented on internal/app/helpers/types.go
> +package helpers
Выполнено

2022-04-30 07:25 UTC, t1mon-ggg commented on internal/app/storage/memory.go
> +	if db == nil {
Выполнено.

2022-04-30 07:26 UTC, t1mon-ggg commented on internal/app/storage/filestorage.go
> +		if len(entry.Short) != 0 {
Выполнено

2022-04-30 07:27 UTC, t1mon-ggg commented on cmd/shortener/shortener.go
> +package main
выполнено

2022-04-30 07:27 UTC, t1mon-ggg commented on cmd/shortener/shortener.go
> +	AppData := webhandlers.NewApp()
выполнено

2022-04-30 07:28 UTC, t1mon-ggg commented on internal/app/webhandlers/handler.go
> +func (db *app) Router(r chi.Router) {
выполнено

2022-04-30 07:28 UTC, t1mon-ggg commented on internal/app/webhandlers/handler.go
> +func DecompressRequest(next http.Handler) http.Handler {
выполнено

2022-04-30 07:28 UTC, t1mon-ggg commented on internal/app/webhandlers/handler.go
> +func TimeTracer(next http.Handler) http.Handler {
выполнено

2022-04-30 07:28 UTC, t1mon-ggg commented on cmd/shortener/shortener.go
> +	AppData := webhandlers.NewApp()
выполнено

2022-04-30 07:29 UTC, t1mon-ggg commented on internal/app/storage/memory.go
> +type MemDB map[string]helpers.WebData
убрал тип Data
выполнено

2022-04-30 07:30 UTC, t1mon-ggg commented on internal/app/storage/memory.go
> +		entry := m[i]
выполнено

2022-04-30 07:32 UTC, t1mon-ggg commented on cmd/shortener/main.go
> +	"github.com/go-chi/chi"
выполнено

2022-05-01 22:58 UTC, t1mon-ggg commented on internal/app/storage/database.go
> +	for i := range data {
выполнено

2022-05-01 22:59 UTC, t1mon-ggg commented on internal/app/helpers/types.go
> +type WebData struct {
полностью отказался от map
провел полную переделку кода в соответствии с новой схемой хранения

2022-05-02 07:43 UTC, asmyasnikov commented on internal/app/config/config.go
> +	cfg.readCli()
Вроде бы по условиям (5го?) инкремента env переменные должны иметь бОльший приоритет. Не знаю почему у тебя тесты проходят...

2022-05-02 07:44 UTC, asmyasnikov approved these changes

2022-05-08 06:57 UTC, closed without merging